name: trigger-demo
on: 
  push:
    branches:
      -main
  workflow_dispatch:
 
jobs:
  trigger-demo:
    runs-on: ubuntu-latest
    steps:
      - name: run results script
        run: |
          pip install -r requirements.txt
          python results_so_far.py
