name: GitHub Actions Demo
on:
  push:
    branches:
      -main
  workflow_dispatch:
jobs:
  first-github-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run python script
        run: |
          pip install -r requirements.txt
          python results_so_far.py
